### ISSUE TITLE
Odroid XU4 compile error

### ISSUE THREAD

**Issue by sydragos** [MatthewVance/nginx-build#1]
There was a small change needed for it to compile on XU4's Ubuntu 14.04 image, adding this to ./config:

`--with-openssl=$BPATH/$VERSION_OPENSSL \`

**Comment by MatthewVance** [comment]
Thanks for letting me know. I'll think about adding it in, but would like to test it to make sure it still works on the Pi (it should). Feel free to send a pull request.

**Comment by MatthewVance** [comment]
I went ahead and added the flag in, but I think the recently released 1.9.12 version of NGINX included a fix for this. The [change log](http://nginx.org/en/CHANGES) stated:

> *) Bugfix: nginx could not be built statically with OpenSSL on Linux;
>        the bug had appeared in 1.9.11.
