### ISSUE TITLE
Script fails on Raspbian Stretch, apparently due to gpg-agent sockets

### ISSUE THREAD

**Issue by GainfulShrimp** [MatthewVance/nginx-build#33]
I've upgraded one of my Pi 2s to Raspbian Stretch, to play around with it.

On this device, the script consistently fails for me immediately after verifying the GPG signatures, when trying to clean up the temporary `$GNUPGHOME` folder. Sample output as follows (actual temp folder name is randomised by mktemp of course):

```
+ rm -r /tmp/tmp.nT906gAGet OPENSSL.tar.gz.asc NGINX.tar.gz.asc
rm: cannot remove '/tmp/tmp.nT906gAGet/S.gpg-agent.extra': No such file or directory
rm: cannot remove '/tmp/tmp.nT906gAGet/S.gpg-agent.ssh': No such file or directory
rm: cannot remove '/tmp/tmp.nT906gAGet/S.gpg-agent.browser': No such file or directory
```

The reason seems to be that gpg in Raspbian Stretch is now on version 2.x (Jessie used 1.x):

```
pi@pi2:/usr/local/src/nginx $ gpg --version
gpg (GnuPG) 2.1.18
libgcrypt 1.7.6-beta
```

It seems gpg automatically starts gpg-agent and this behaviour cannot be disabled using the `--no-use-agent` option in GnuPG 2.x, as [explained in the docs](https://www.gnupg.org/documentation/manuals/gnupg/GPG-Configuration-Options.html):

> `--use-agent`
> `--no-use-agent`
> This is dummy option. gpg always requires the agent.
 
gpg-agent creates the three sockets in `$GNUPGHOME`, as above.
At the time the script subsequently tries to clean up the temp folder (using `rm -f`), the sockets are still there, and `rm` thus complains that it can't delete them, as shown in the above error output. (The sockets are certainly gone by the time I try looking for them after the script has exited on failure though!)

I've found that the error goes away if I specifically quit the gpg-agent process before attempting to delete the temp folder, by adding a `gpgconf --kill gpg-agent` line immediately before the `rm -r "$GNUPGHOME" OPENSSL.tar.gz.asc NGINX.tar.gz.asc` line.

I'm happy to raise a PR for adding this extra line, but thought it was worth discussing in an issue first... especially as I'm not very familiar with GnuPG!

**Comment by MatthewVance** [comment]
Thanks for this. I haven't upgraded my Pi yet, but can confirm I had a GNUPG issue with my Docker NGINX container when I upgraded it to Stretch. 

Here's how I fixed it there: 
https://github.com/MatthewVance/nginx-docker/commit/e165fa9855b0dfc7e4575370597142c1040b7090

This may be a different issue though. The Stretch Docker base image didn't have GPG at all. Did you start with a fresh Pi image for Stretch or upgrade your existing install?

I need to look into this more. It will be a while before I have time. We might merge your one line fix and replace it later if we find a better solution. It might be good to also add a line near the end to re-start the agent. Thoughts?

**Comment by GainfulShrimp** [comment]
Sorry for the delay in responding.  I agree it looks like your Docker issue was something else - i.e. that GnuPG was not available at all.  Also agree that it could do with some further looking/analysis... preferably by someone who's used `gpg` more than I have! ;)

I upgraded an existing image rather than fresh install, before the Stretch image was officially released (but after it was available in the repos) which perhaps makes it an unusual (perhaps unrepresentative) build.  (I've since updated it though, of course.)

From my Googling around the subject, I don't believe it's necessary to re-start the agent near the end, as `gpg` starts `gpg-agent` on-demand, when necessary (i.e. if it's not already running).  If it was already running, before the script kicked it off, presumably the sockets would be somewhere else - because the temporary $GNUPGHOME is only created in the previous line or two of the script?

Next time I need a Raspberry Pi build from scratch, I'll use an official Raspbian Stretch image, but that might not be for a while.

**Comment by GainfulShrimp** [comment]
Apologies, but I think this might be something specific to this device/build rather than the build-nginx.sh script...
Today I ran `build-nginx.sh` on a Pi3 which is also running Raspbian Stretch (also upgraded from Jessie, rather than clean install) and it worked flawlessly, without any changes.

**Comment by MatthewVance** [comment]
Thanks for the update. I haven’t had a chance to test on my Pi yet. I plan to upgrade to Stretch rather than start fresh so it may not be the cleanest of test, but I’m curious to see how it compares to your results.

**Comment by jellemdekker** [comment]
I successfully ran the script on a Raspberry Pi 2 Model B on a clean install of Raspbian Stretch and it works flawlessly. Thank you for your work @MatthewVance and @GainfulShrimp. This issue can be closed.

**Comment by MatthewVance** [comment]
Great. Thanks for letting me know.
