### ISSUE TITLE
gpg: keyserver receive failed: Cannot assign requested address

### ISSUE THREAD

**Issue by johnbritto1** [MatthewVance/nginx-build#54]
gpg --batch --verify OPENSSL.tar.gz.asc OPENSSL.tar.gz
gpg: Signature made Tue Mar 27 13:50:44 2018 UTC
gpg:                using RSA key D9C4D26D0E604491
gpg: Good signature from "Matt Caswell <matt@openssl.org>" [unknown]
gpg:                 aka "Matt Caswell <frodo@baggins.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 8657 ABB2 60F0 56B1 E519  0839 D9C4 D26D 0E60 4491
gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B0F4253373F8F6F510D42178520A9993A1C052F8

**Comment by johnbritto1** [comment]
Found a solution: Changing the keyserver from ha.pool.sks-keyservers.net  to ipv4.pool.sks-keyservers.net  works.

**Comment by MatthewVance** [comment]
Ok. Re-running the script with the original key server should also work.
Sometimes it doesn't respond correctly (likely an issue with a node in the
pool). I've found most times trying again a time or two causes it to go
through correctly.
