### ISSUE TITLE
can't reach openssl

### ISSUE THREAD

**Issue by realies** [MatthewVance/nginx-build#57]
It seems `www.openssl.org` resolves at `2a02:26f0:8f:18f::c1e`, ipv6 is disabled by default on raspbian, anyone else getting the following?

```
+ curl -L https://www.openssl.org/source/openssl-1.1.0h.tar.gz -o /home/pi/install/build/OPENSSL.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Couldn't connect to server
+ curl -L https://www.openssl.org/source/openssl-1.1.0h.tar.gz.asc -o /home/pi/install/build/OPENSSL.tar.gz.asc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Couldn't connect to server
```

**Comment by MatthewVance** [comment]
I haven't seen that before on Raspbian. It's been a while since I've
compiled it on my Pi so maybe it's something with a new update. I know
Raspbian had a pretty big update recently, but didn't think it had anything
to do with networking.

The only network issue I've seen with the script is when receiving GPG keys
from the ha.pool.sks-keyservers.net pool. Sometimes that fails, but
re-running the script a time or two usually resolves it. My guess is it
depends on which node in the pool you get.

What happens if you hard code the IP4 address of openssl.org in your
/etc/hosts file?

**Comment by realies** [comment]
Adding the ipv4 address to hosts and rebooting doesn't resolve it, curl still trying to find it via ipv6.

```
$ tail -n2 /etc/hosts
67.215.92.210 www.opendns.org
67.215.92.210 opendns.org
```

```
$ curl -vvvv https://www.openssl.org/source/openssl-1.1.0h.tar.gz.asc
*   Trying 2a02:26f0:8f:190::c1e...
* TCP_NODELAY set
* Immediate connect fail for 2a02:26f0:8f:190::c1e: Network is unreachable
*   Trying 2a02:26f0:8f:18f::c1e...
* TCP_NODELAY set
* Immediate connect fail for 2a02:26f0:8f:18f::c1e: Network is unreachable
* Closing connection 0
curl: (7) Couldn't connect to server
```

**Comment by MatthewVance** [comment]
Why do you have opeendns in your host file?

**Comment by realies** [comment]
No idea. Pinging `openssl.org` resolves the hostname `dev.openssl.org`, doing a DNS lookup for `www.openssl.org` shows an ipv6 address. Don't think they have an ipv4 for `www.openssl.org`.

**Comment by MatthewVance** [comment]
I get 172.224.192.29 back. My network is both IPv4 and IPv6. 

```
 nslookup www.openssl.org
;; Got SERVFAIL reply from 192.168.1.24, trying next server
Server:		9.9.9.9
Address:	9.9.9.9#53

Non-authoritative answer:
www.openssl.org	canonical name = www-ds.openssl.org.edgekey.net.
www-ds.openssl.org.edgekey.net	canonical name = e3102.dscx.akamaiedge.net.
Name:	e3102.dscx.akamaiedge.net
Address: 172.224.192.29
```

**Comment by realies** [comment]
Using `nslookup` revealed the IPv4 address indeed. Unfortunately the script stopped at
```
+ rm -r /tmp/tmp.xoG1pHkUCN OPENSSL.tar.gz.asc NGINX.tar.gz.asc
rm: cannot remove '/tmp/tmp.xoG1pHkUCN/S.gpg-agent.extra': No such file or directory
```

**Comment by MatthewVance** [comment]
This appears to be an issue specific to your setup and not the script. I just tested on a fairly clean and up-to-date version of Raspbian and build worked without any errors.

**Comment by realies** [comment]
This is on a fresh and upgraded Raspbian.

**Comment by MatthewVance** [comment]
That’s basically what mine was as well though I’m running headless with stretch lite. I ran apt update and upgrade before building. I’ve barely used the Pi since recently re-installing the OS and hardening it. I also have not seen any other reports of similar issues. You are running the script as published verbatim, right? No -j, etc.

**Comment by realies** [comment]
The `-j` argument is after `rm -r "$GNUPGHOME" OPENSSL.tar.gz.asc NGINX.tar.gz.asc`, which is where it stops. Nevertheless, I can confirm it happens with the script that is provided in this repo.

Here is the whole log: https://dpaste.de/ErGm/raw

**Comment by MatthewVance** [comment]
Look at this too: https://github.com/MatthewVance/nginx-build/issues/33

**Comment by MatthewVance** [comment]
The full log helped. Looking at this more, something like this came up last year shortly after Debian Stretch was released. That's the issue I referenced a minute ago. After reviewing and thinking some more try doing what @GainfulShrimp did. He added a `gpgconf --kill gpg-agent` line immediately before the `rm -r "$GNUPGHOME" OPENSSL.tar.gz.asc NGINX.tar.gz.asc` line.

**Comment by realies** [comment]
Adding `gpgconf --kill gpg-agent` before `rm -r "$GNUPGHOME" OPENSSL.tar.gz.asc NGINX.tar.gz.asc` resolves it. Should I follow this with a PR?

**Comment by MatthewVance** [comment]
Not at this time.
