### ISSUE TITLE
Is it possible to actually use TLS 1.3 with Nginx 1.15.3 and OpenSSL 1.1.1?

### ISSUE THREAD

**Issue by GainfulShrimp** [MatthewVance/nginx-build#62]
I've used the latest version of the script to build a brand-spanking nginx, with the above package versions, then tried to convert my existing (TLS 1.2 based) config to use TLS 1.3, but Chrome (Windows 10, Version 69.0.3497.81 (Official Build) (64-bit)) is telling me I'm still connecting via TLS 1.2.  My Mac version of Chrome (can't recall the version right now) also states it's using TLS 1.2.

An ssllabs test also reports that TLS 1.3 is not supported by my site... so it seems that I'm doing something wrong?

I believe these are the relevant items in my nginx config:

```
        ssl_session_cache shared:SSL:32m;
        ssl_buffer_size 8k;
        ssl_session_timeout 1d;
        ssl_session_tickets off;
        ssl_ecdh_curve X25519:secp256k1:secp384r1:prime256v1;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers 'TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
        ssl_prefer_server_ciphers on;
```

If I try to force TLS 1.3 using the line `ssl_protocols TLSv1.3;`, then Chrome complains with `ERR_SSL_VERSION_OR_CIPHER_MISMATCH`.

I have also tried commenting out most of the above config, thus using the defaults for curves and ciphersuites etc, just keeping `ssl_protocols TLSv1.3;`... this also fails with the same error.

Unsurprisingly, for something so new, I can only find blogs/articles/issues around using the beta or pre versions of OpenSSL which were capable of TLS 1.3 support, not v1.1.1 (the first 'production ready' OpenSSL release to support it).  I'm aware that others have used BoringSSL with some success, but I'd rather hang out for a working OpenSSL setup tbh.

I've found a few clues suggesting that maybe there are code changes needed in nginx to enable the new API which openssl implemented, in order to avoid accidental disabling of TLS 1.3 via explicit use of 'legacy' ciphersuite values?

https://github.com/ssllabs/ssllabs-scan/issues/636
https://trac.nginx.org/nginx/ticket/1529

So really, this issue could be rephrased as a question: *"Has anyone successfully used this version of the nginx-build script to do TLS 1.3?"*

**Comment by GainfulShrimp** [comment]
Hmm... after a bit more Googling, it seems that both SSLLabs and Chrome 69 only support the Draft 28 version of TLS 1.3, **not** the final version.  OpenSSL 1.1.1 has removed support for the draft versions and only supports the final version, hence why the fallback to TLS 1.2 occurs.

If I use OpenSSL's own client to connect to my server, it can connect just fine using TLS 1.3:

```
openssl s_client -connect mydomain.com:443 -tls1_3
```

So it seems that it's not an issue with my server config but rather that I wasn't using a sufficiently-bleeding-edge client to actually negotiate TLS 1.3 using the final standard.

**Comment by GainfulShrimp** [comment]
Just to close this off, I thought I'd attach instructions on how to verify your TLS 1.3 (Final) server is indeed capable of TLS 1.3, using Chrome Canary - i.e. a pre-release nightly build version of Chrome...

1. Visit the [Chrome Canary download page](https://www.google.com/intl/en_uk/chrome/canary/) to get the installer. I got version Version 71.0.3550.0 (Official Build) canary (64-bit) just now, but I think anything after v70 should work.
2. Install as usual, then visit the following special URL `chrome://flags/#tls13-variant`
3. Select **Enabled (Final)** from the dropdown box.
4. Restart as prompted.
5. Visit your site, and press cmd+opt+I if on Mac (or press F12 if using Windows or Linux), to open Chrome Dev Tools.
6. In the *Security* tab, you should now find confirmation that TLS 1.3 is being used for the connection...

![screen shot 2018-09-12 at 15 59 59](https://user-images.githubusercontent.com/18337123/45433919-1ef48300-b6a5-11e8-9615-ec2c693e4fff.png)

**Comment by MatthewVance** [comment]
Thank you for the reports and follow-ups.
