### ISSUE TITLE
OpenSSL OPGP Signature Check Failure

### ISSUE THREAD

**Issue by MatthewVance** [MatthewVance/nginx-build#79]
With the release of OpenSSL 1.1.1c, the digitial siganture verification is failing. The error message is "gpg: Can't check signature: No public key".

**Comment by MatthewVance** [comment]
Richard Levitt signed this release of OpenSSL rather than Matt Caswell. Updating the `opgp_openssl` variable to `7953AC1FBC3DC8B3B292393ED5E9E43F7DF9EE8C` is a short-term workaround. 

Longer-term, the script should be revised to automatically handle releases signed by any of the authorized OMC members. [OMC](https://www.openssl.org/community/omc.html) members who currently sign releases are noted at https://www.openssl.org/source/.

**Comment by MatthewVance** [comment]
Committed https://github.com/MatthewVance/nginx-build/commit/d78f68b08871ca27f68bba92d3de688b458336b2 at short-term fix.

**Comment by fabianegli** [comment]
I experience a similar problem with the pcre signature:

```
gpg --keyserver ipv4.pool.sks-keyservers.net --recv-keys 45F68D54BBE23FB3039B46E59766E084FB0F43D8 5ED46A6721D365587791E2AA783FCD8E58BCAFBA 7953AC1FBC3DC8B3B292393ED5E9E43F7DF9EE8C B0F4253373F8F6F510D42178520A9993A1C052F8
gpg: keybox '/tmp/tmp.6BhyXMhdSM/pubring.kbx' created
gpg: key 520A9993A1C052F8: 6 signatures not checked due to missing keys
gpg: /tmp/tmp.6BhyXMhdSM/trustdb.gpg: trustdb created
gpg: key 520A9993A1C052F8: public key "Maxim Dounin <mdounin@mdounin.ru>" imported
gpg: key D5E9E43F7DF9EE8C: 60 signatures not checked due to missing keys
gpg: key D5E9E43F7DF9EE8C: public key "Richard Levitte <richard@levitte.org>" imported
gpg: key 783FCD8E58BCAFBA: 3 signatures not checked due to missing keys
gpg: key 783FCD8E58BCAFBA: public key "Mark Adler <madler@alumni.caltech.edu>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 3
gpg:               imported: 3
+ gpg --batch --verify pcre.tar.gz.sig pcre.tar.gz
gpg: Signature made Sat 23 Feb 2019 05:44:28 PM CET
gpg:                using RSA key 45F68D54BBE23FB3039B46E59766E084FB0F43D8
gpg: Can't check signature: No public key
```

The public key is published at the download site https://ftp.pcre.org/pub/pcre/Public-Key

**Comment by MatthewVance** [comment]
Interesting. That is the same error message. Can you reproduce this error
consistently?

I ask because as far as I know, the PCRE version hasn't changed since
February of this year (thus the signature shouldn't have changed either)
and I was able to successfully run the build script the other day after
making the change for OpenSSL.

**Comment by fabianegli** [comment]
Indeed, running it again (the identical script) worked. I wonder if this was a gpg bug/issue/feature?

**Comment by MatthewVance** [comment]
I'm glad it worked. It could be issue with the key server pool or a brief
network issue. In the past, issues like this occurred periodically. I
eventually made a change to add a fall back that seems to have
significantly reduced how often this occurs.

The following was the change:
https://github.com/MatthewVance/nginx-build/commit/6228aef4e8f77fce400f31d88763d1b4e6d20a3a
