### ISSUE TITLE
OpenSSL signature verification consistently failing (again)

### ISSUE THREAD

**Issue by GainfulShrimp** [MatthewVance/nginx-build#80]
It seems that Matt Caswell signed the latest openssl the other day (1.1.1d), which means the script is failing consistently, similarly to [Issue 79](https://github.com/MatthewVance/nginx-build/issues/79):
```
+ gpg --batch --verify openssl.tar.gz.asc openssl.tar.gz
gpg: Signature made Tue 10 Sep 2019 14:13:14 BST
gpg:                using RSA key 8657ABB260F056B1E5190839D9C4D26D0E604491
gpg: Can't check signature: No public key
```
As I'm not brave enough to attempt the robust/long-term "support all keys used by the openssl team" solution suggested by @MatthewVance in that issue, for now, I'll submit a PR to switch the key back again. At least that gets the script working again. ;)

**Comment by GainfulShrimp** [comment]
I've submitted a [PR](https://github.com/MatthewVance/nginx-build/pull/81) to get the script working again for now.

**Comment by MatthewVance** [comment]
Thanks. I had to do the same thing on my Unbound container. Sorry I forgot to update the value on this script as well. I appreciate the PR.

**Comment by miloscvj** [comment]
Hi for all, 

Matthew I am facing a similar error when I ran build_nginx.sh.


+ gpg --batch --verify openssl.tar.gz.asc openssl.tar.gz
gpg: Signature made Tue 08 Apr 2025 03:14:28 PM CEST
gpg:                using RSA key BA5473A2B0587B07FB27CF2D216094DFD0CB81EF
gpg: Can't check signature: No public key
