### ISSUE TITLE
/etc/nginx/modules/ngx_http_auth_pam_module.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by designandsolutions** [MatthewVance/nginx-build#83]
I was previously using the version of Nginx available via latest Raspbian release (v1.14.2).

I ran through your instructions exactly as described and it appeared to complete successfully, it reports that Nginx is v1.17.9, however, now my instance of Nginx will not start anymore.

> sudo systemctl status nginx
â—� nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2020-03-04 22:43:16 GMT; 1h 17min ago
     Docs: man:nginx(8)
  Process: 16246 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)

Mar 04 22:43:16 das-svr-nginx systemd[1]: Starting A high performance web server and a reverse proxy server...
Mar 04 22:43:16 das-svr-nginx nginx[16246]: nginx: [emerg] dlopen() "/etc/nginx/modules/ngx_http_auth_pam_module.so" failed (/etc/nginx/modules/ngx_http_auth_pam_module.so: cannot open shared object file: No such file or directory) in /etc/nginx/modules-enabled/50-mod-http-auth-pam.conf:1
Mar 04 22:43:16 das-svr-nginx nginx[16246]: nginx: configuration file /etc/nginx/nginx.conf test failed
Mar 04 22:43:16 das-svr-nginx systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Mar 04 22:43:16 das-svr-nginx systemd[1]: nginx.service: Failed with result 'exit-code'.
Mar 04 22:43:16 das-svr-nginx systemd[1]: Failed to start A high performance web server and a reverse proxy server. <

As far as i am aware i am not using this module in my conf or sites

**Comment by MatthewVance** [comment]
Are any of your sites using HTTP Basic Authentication (particularly via PAM)? The error implies the issue is related to something in `/etc/nginx/nginx.conf`. Can you share a copy of that (feel free to redact as necessary)?

Another option is to modify the script to include [ngx_http_auth_pam_module](https://github.com/sto/ngx_http_auth_pam_module), re-build, and see if it starts normally again. If so, it would further indicate something in your environment needs that. 

It is interesting because that particular module is a [3rd party one](https://www.nginx.com/resources/wiki/modules/) and I wouldn't expect that to be included in the version of Nginx available via latest Raspbian release.

**Comment by MatthewVance** [comment]
Looking at the [Debian package for nginx](https://packages.debian.org/buster/nginx-full), it looks like that third-party module is included. Since Raspbian essentially uses the Debian's package repo as an upstream source, it's safe to assume the Raspbian version would also have it so my prior comment about not expecting that 3rd party repo to be included was wrong.

**Comment by designandsolutions** [comment]
Thanks for the fast response.

Here is the nginx.conf i am using:
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 768;
	# multi_accept on;
}

http {

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	server_tokens off;

	server_names_hash_bucket_size 128;
	# server_name_in_redirect off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# SSL Settings
	##
	
	ssl_session_cache shared:SSL:10m;
	ssl_protocols TLSv1.2; # Dropping SSLv3, ref: POODLE, dropping tls1.0 and 1.1
	ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4:!SHA1:!DHE;
	ssl_prefer_server_ciphers on;

	ssl_certificate ###/server.crt;
	ssl_certificate_key ###/server.key;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	##
	# Gzip Settings
	##

	gzip on;
	gzip_disable "msie6"; 

	# gzip_vary on;
	# gzip_proxied any;
	# gzip_comp_level 6;
	# gzip_buffers 16 8k;
	# gzip_http_version 1.1;
	# gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

	##
	# Virtual Host Configs
	##

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
}


#mail {
#	# See sample authentication script at:
#	# http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
# 
#	# auth_http localhost/auth.php;
#	# pop3_capabilities "TOP" "USER";
#	# imap_capabilities "IMAP4rev1" "UIDPLUS";
# 
#	server {
#		listen     localhost:110;
#		protocol   pop3;
#		proxy      on;
#	}
# 
#	server {
#		listen     localhost:143;
#		protocol   imap;
#		proxy      on;
#	}
#}

**Comment by MatthewVance** [comment]
This stood out to me: include /etc/nginx/modules-enabled/*.conf;

What's in that?

**Comment by designandsolutions** [comment]
Sorry, you'll have to forgive my lack of experience with this. It maybe an issue that i installed the latest version of Nginx over the top of the Debian version (where i should have uninstalled it first).

This is the contents of the folder:
![image](https://user-images.githubusercontent.com/18214426/75992124-6bfa9380-5eef-11ea-83c9-5bb4fb6eb630.png)

There is nothing in the modules-available folder, so i am guessing i need to remove all of these?

**Comment by MatthewVance** [comment]
Yes, that's likely the issue. You could probably just remove the unneeded
conf file.

**Comment by designandsolutions** [comment]
Commenting the line allows Nginx to start.

Thank you for your help.

**Comment by MatthewVance** [comment]
Great. I'm glad everything is working again for you.
