### ISSUE TITLE
gpg: keyserver receive failed: No name

### ISSUE THREAD

**Issue by GiovanniBattista** [MatthewVance/nginx-build#86]
Today I was building nginx for a new setup and encountered the following issue:
```
+ GNUPGHOME=/tmp/tmp.f9mK4zGCSB
+ export GNUPGHOME
+ gpg --keyserver ipv4.pool.sks-keyservers.net --recv-keys 45F68D54BBE23FB3039B46E59766E084FB0F43D8 5ED46A6721D365587791E2AA783FCD8E58BCAFBA 8657ABB260F056B1E5190839D9C4D26D0E604491 B0F4253373F8F6F510D42178520A9993A1C052F8
gpg: keybox '/tmp/tmp.f9mK4zGCSB/pubring.kbx' created
gpg: keyserver receive failed: No name
+ gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 45F68D54BBE23FB3039B46E59766E084FB0F43D8 5ED46A6721D365587791E2AA783FCD8E58BCAFBA 8657ABB260F056B1E5190839D9C4D26D0E604491 B0F4253373F8F6F510D42178520A9993A1C052F8
gpg: keyserver receive failed: No name
```
This has probably to do with the SKS network being deprecated as it was stated [here in this SO answer](https://stackoverflow.com/questions/66217436/gpg-keyserver-receive-failed-no-name).

If I replace the used keyserver with "keyserver.ubuntu.com", then the script works.

**Comment by MatthewVance** [comment]
@GiovanniBattista thanks for reminding me to update this. You're correct that the issue is related to the deprecation of the SKS keyservers. 

If interested, this page explains why the service is deprecated: https://sks-keyservers.net/status/

**Comment by GiovanniBattista** [comment]
Thanks for the info 👍
