### ISSUE TITLE
 ftp.pcre.org FTP site is no longer available.

### ISSUE THREAD

**Issue by petter5** [MatthewVance/nginx-build#87]
The former ftp.pcre.org FTP site is no longer available. You will need to update the script.

**Comment by johnbritto1** [comment]
Hi,

I use 
export SOURCE_PCRE=https://onboardcloud.dl.sourceforge.net/project/pcre/pcre/8.45/
export VERSION_PCRE=pcre-8.45

Hope that help.

**Comment by MatthewVance** [comment]
Thank you both.
